### ISSUE TITLE
Howto set private token header

### ISSUE THREAD

**Issue by zzOzz** [afragen/git-updater-gitlab#2]
I've got a private gitlab-ce server with a wordpress theme project

I don't understand how can I set private token header to update theme ?

this is the style.css header 

~~~
/*!
Theme Name: Prairial Neve Child
Theme URI: https://git.mydomain/wordpress/sites/prairial.git
GitLab Theme URI: https://git.mydomain/wordpress/sites/prairial.git
Template: neve
…
~~~

**Comment by afragen** [comment]
You enter the URI to the private GitLab repository. As you have done. You will need to enter the personal access token in the GitLab settings tab as well. 

Make sure you use a Primary Branch header if the primary branch is not master. 

https://git-updater.com has loads of info.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/self-hosted-enterprise-git-hosts/#articleTOC_2

**Comment by zzOzz** [comment]
I cannot find where do I put the access token on the plugin side ?

**Comment by afragen** [comment]
Can you post a screenshot of the Git Updater settings page? Specifically the GitLab tab.

**Comment by zzOzz** [comment]
You can close this issue.

I found that I have a bug in my wordpress install (gitupdater doesn't activate correctly)

I forgot
->
Primary Branch: main

I miss "nocanon"  Option in my apache gitlab reverse proxy. (same bug as https://gitlab.com/gitlab-org/gitlab-foss/-/issues/44214)

But now I works !!!

Thanks a lot.
