### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by tharbad08** [afragen/git-updater-gitlab#3]
Hi,

I'm getting 404 error. 

Query monitor location:

`    wp-content/plugins/git-updater-gitlab/src/GitLab/GitLab_API.php:293
    Fragen\G\A\GitLab_API->get_gitlab_id()
    wp-content/plugins/git-updater-gitlab/src/GitLab/GitLab_API.php:75
    Fragen\G\A\GitLab_API->get_remote_info()
    wp-content/plugins/git-updater/src/Git_Updater/Base.php:328
    Fragen\Git_Updater\Base->get_remote_repo_meta()
    wp-content/plugins/git-updater/src/Git_Updater/Plugin.php:288
    Fragen\Git_Updater\Plugin->get_remote_plugin_meta()
    wp-content/plugins/git-updater/src/Git_Updater/Base.php:186
    Fragen\Git_Updater\Base->get_meta_plugins()
    wp-content/plugins/git-updater/src/Git_Updater/Base.php:176
    Fragen\Git_Updater\Base->load()
    wp-includes/class-wp-hook.php:308
    do_action('init')
    wp-settings.php:617`

Error message: 

`Undefined property: stdClass::$path`

`GitLab Plugin URI: https://gitlab.com/<group>/<sub group>/<project>`

**Comment by afragen** [comment]
Can you share the repo URL? If private, can you temporarily add `afragen` as a contributor?

**Comment by tharbad08** [comment]
Can't give you permission to that specific repo. Gave you permissions to a blank repo. Under the same subgroup. Maintainer permissions.

**Comment by afragen** [comment]
A blank repo doesn’t help, I’m sorry. Can you post the actual URL to the repo, post the tree structure of the repo and post the main plugin file headers.

**Comment by tharbad08** [comment]
.
├── admin
│   ├── class-iframe-inserter-admin.php
│   ├── css
│   │   └── iframe-inserter-admin.css
│   ├── iframe_tinymce_btn_lang.php
│   ├── index.php
│   └── js
│       └── iframe.js
├── iframe-inserter.php
├── includes
│   ├── class-iframe-inserter-activator.php
│   ├── class-iframe-inserter-deactivator.php
│   ├── class-iframe-inserter-i18n.php
│   ├── class-iframe-inserter-loader.php
│   ├── class-iframe-inserter.php
│   └── index.php
├── index.php
├── languages
│   ├── iframe-inserter-he_IL.mo
│   ├── iframe-inserter-he_IL.po
│   └── plugin-name.pot
├── LICENSE.txt
├── public
│   ├── class-iframe-inserter-public.php
│   ├── index.php
│   └── js
│       └── iframe-inserter-public.js
├── README.txt
└── uninstall.php


Header:
`
/**
 * The plugin bootstrap file

 * @link              http://leketshibolim.ort.org.il/
 * @since             1.0.0
 * @package           IFrame Inserter
 *
 * @wordpress-plugin
 * Plugin Name:       IFrame Inserter
 * Plugin URI:        http://leketshibolim.ort.org.il/iframe-inserter-uri/
 * Description:       Inserts Iframe in a post.
 * Version:           1.1.0
 * Author:            Lea Cohen
 * Author URI:        http://leketshibolim.ort.org.il/
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       iframe-inserter
 * Domain Path:       /languages
 * Update URI: 		  iframe-inserter
 * Primary Branch: main
 * GitLab Plugin URI: https://gitlab.com/OrtIsraelRD/wp-dev/p-iframe-inserter
 */
`

**Comment by afragen** [comment]
What is the plugin slug? Because the way it's setup it will be `wp-dev`

**Comment by tharbad08** [comment]
Should be `p-iframe-inserter`

`wp-dev` is the sub group.

**Comment by afragen** [comment]
I was incorrect above. It should work. I have a Gitlab repo in a `<group>/<sub-group>` that I test with and it works.

Without testing with the actual repository I can only say that a 404 error is usually an invalid access token. Take a look at the Troubleshooting section, https://git-updater.com/knowledge-base/troubleshooting/ and see if there are any HTTP errors from Query Monitor.

**Comment by tharbad08** [comment]
Been there b4 I opened this issue.

Before I try again with the same tokens. Which api permission those gitlab token need?
That seems like the only other problem I can think of.

**Comment by afragen** [comment]
Token needs read permission for most things. I don't specifically remember what the options for GitLab are. Create a token with full access to everything and see what happens. Git Updater does write anything upstream, it only updates/replaces the downstream code with the upstream code.

**Comment by afragen** [comment]
It might be that the `api` is the only one necessary. But I’d add anything that has read or read/write.

**Comment by tharbad08** [comment]
Ok. Culprit found: 
Branch name is master and not main.

I tested permissions too:
User: read_api, read_repository
Project: read_api, read_repository as Reporter

Note that starting from gitlab 16.0 (upcoming version), Expiration date for both tokens is mandatory.

Can you add this to the docs?

Also, while testing, I noticed that changing the user token after updating the plugin will result in red ! near the plugin name. But Query manager showed no errors and gitlab gui didn't show any attempt to use the token.
Had to delete the target plugin and re upload it.

**Comment by afragen** [comment]
I've cached errors for an hour, that's likely why you might still see the red warning icon. You can Refresh Cache to clear that.

I didn't know about the expiration date for GitLab tokens, I'll make a note.

**Comment by tharbad08** [comment]
The red ! showed even after a cache refresh

**Comment by afragen** [comment]
I bet the primary branch was saved in the database. This being the incorrect primary branch. In the near future a web hook will be available to reset this. 

https://git-updater.com/knowledge-base/remote-management-restful-endpoints/#articleTOC_2

Next major release will include these features in core plugin.

**Comment by tharbad08** [comment]
Thanks!
